from pathlib import Path
p=Path('docs/movement/app.mjs')
s=p.read_text(encoding='utf-8').replace('v=16','v=17').replace('{HeadLook}','{HeadLook,bodyDisplacement}')
s=s.replace('const yaw=camera.rotation.y;dustMap.move(camera.position,Math.cos(yaw)*r.dx+Math.sin(yaw)*r.dz,-Math.sin(yaw)*r.dx+Math.cos(yaw)*r.dz);','const step=bodyDisplacement(r.dx,r.dz,headLook.heading);dustMap.move(camera.position,step.x,step.z);')
s=s.replace('lastFrameTime=0;','lastFrameTime=0,handsSinceHead=0;')
s=s.replace("if(running&&head?.wantsFrame(lastResult)","handsSinceHead++;if(running&&handsSinceHead>=2&&head?.wantsFrame(lastResult)")
s=s.replace("{lastHeadVideo=$('cam').currentTime;head.capture", "{handsSinceHead=0;lastHeadVideo=$('cam').currentTime;head.capture")
s=s.replace('interval:50','interval:100')
s=s.replace('headLook.speed=0;head?.worker','headLook.resetLook();head?.worker')
s=s.replace('head?.recenter();headLook.speed=0;swipe.reset();','head?.recenter();headLook.resetLook();swipe.reset();')
s=s.replace("headLook.speed=0;head?.recenter();", "headLook.resetLook();head?.recenter();camera.rotation.y=headLook.heading;")
s=s.replace('headLook.heading=0;lookDemo=0;', 'headLook.heading=0;headLook.resetLook();lookDemo=0;')
s=s.replace("$('headThreshold').oninput", "$('turnMode').onchange=()=>{headLook.mode=$('turnMode').value;headLook.resetLook();head?.recenter();};\n$('headThreshold').oninput")
a=s.index("$('hint').textContent=");b=s.index(';status(',a)
s=s[:a]+"$('hint').textContent='LEFT index out: move your hand to walk. Bend index to release and reposition. Push toward camera = forward; pull = back. Looking does not redirect walking. Hold a head turn past 12° briefly to rotate your body; centre stops it. Controls also offers Quick flick: slow turns look, quick outward turns rotate the body once; centre to rearm.'"+s[b:]
s=s.replace("headLook.update(rawYaw,dt,valid);if(valid)camera.rotation.set(pose.pitch,headLook.heading,0,'YXZ');", "const viewYaw=headLook.update(rawYaw,dt,valid,head.lastResult?.ts);if(valid)camera.rotation.set(pose.pitch,viewYaw,0,'YXZ');")
s=s.replace("` · turn ${Math.round(Math.abs(headLook.speed)*180/Math.PI)}°/s`", "` · ${headLook.state}${headLook.state==='HOLD TO TURN'?' '+Math.round(headLook.progress*100)+'%':''}`")
s=s.replace("if(demo&&lookDemo){", "if(demo){")
s=s.replace("if(!lookDemo)headLook.speed=0;", "if(!lookDemo)headLook.speed=0;")
p.write_text(s,encoding='utf-8')
p=Path('docs/movement/index.html');s=p.read_text(encoding='utf-8').replace('v=16','v=17').replace('STEADY LOOK · 16','FREE LOOK · 17')
s=s.replace('<label>Turn threshold', '<label>Body turn <select id="turnMode" aria-label="Body turn mode"><option value="hold">Hold past threshold</option><option value="quick">Quick flick (experimental)</option></select></label><label>Turn threshold')
p.write_text(s,encoding='utf-8')
p=Path('docs/movement/map.mjs');s=p.read_text(encoding='utf-8').replace('if(m.isMesh){','if(m.isMesh){m.geometry.computeBoundingBox();')
p.write_text(s,encoding='utf-8')
